steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/quote-builder-loadtrax/cloud-run-source-deploy/quote-builder:latest'
      - '--build-arg'
      - 'VITE_GOOGLE_MAPS_API_KEY=$_VITE_GOOGLE_MAPS_API_KEY'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/quote-builder-loadtrax/cloud-run-source-deploy/quote-builder:latest'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'quote-builder'
      - '--image'
      - 'asia-south1-docker.pkg.dev/quote-builder-loadtrax/cloud-run-source-deploy/quote-builder:latest'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'asia-south1-docker.pkg.dev/quote-builder-loadtrax/cloud-run-source-deploy/quote-builder:latest'
options:
  logging: CLOUD_LOGGING_ONLY
